/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IndicatorParams: typeof import('./src/components/IndicatorParams.vue')['default']
    IndicatorSelector: typeof import('./src/components/IndicatorSelector.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart.vue')['default']
    KLineTooltip: typeof import('./src/components/KLineTooltip.vue')['default']
    MarkerTooltip: typeof import('./src/components/MarkerTooltip.vue')['default']
  }
}
